package cmd

func init() {
	rootCmd.AddCommand(ipCmd)
	rootCmd.AddCommand(portCmd)
	rootCmd.AddCommand(psCmd)
	rootCmd.AddCommand(connCmd)
	rootCmd.AddCommand(connectCmd)
	rootCmd.AddCommand(killCmd)
	rootCmd.AddCommand(dnsCmd)
	rootCmd.AddCommand(pingCmd)
	rootCmd.AddCommand(tracerouteCmd)
	rootCmd.AddCommand(scanCmd)
	rootCmd.AddCommand(httpCmd)
	rootCmd.AddCommand(httpsCheckCmd)
	rootCmd.AddCommand(whoisCmd)
	rootCmd.AddCommand(pstreeCmd)
	rootCmd.AddCommand(pssearchCmd)
	rootCmd.AddCommand(psportsCmd)
	rootCmd.AddCommand(sysinfoCmd)
	rootCmd.AddCommand(memCmd)
	rootCmd.AddCommand(cpuCmd)
	rootCmd.AddCommand(diskCmd)
	rootCmd.AddCommand(ifaceCmd)
	rootCmd.AddCommand(publicipCmd)
	rootCmd.AddCommand(lookupCmd)
	rootCmd.AddCommand(netstatCmd)
	rootCmd.AddCommand(listenCmd)
	rootCmd.AddCommand(speedtestCmd)
	rootCmd.AddCommand(updateCmd)
	rootCmd.AddCommand(completionCmd)
	rootCmd.AddCommand(versionCmd)
	rootCmd.AddCommand(docCmd)
}