package cmd

import (
	"fmt"
	"net"
	"os"
	"runtime"
	"text/template"
	"time"

	"github.com/spf13/cobra"
)

var htmlReportCmd = &cobra.Command{
	Use:   "html_report <output_file>",
	Short: "Generate HTML report",
	Long:  `Generate an HTML report of system and network status.`,
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		outputFile := args[0]
		generateHTMLReport(outputFile)
	},
}

func generateHTMLReport(outputFile string) {
	htmlTemplate := `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>acli System Report</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #e2e8f0; line-height: 1.6; }
        .container { max-width: 1200px; margin: 0 auto; padding: 20px; }
        h1 { color: #38bdf8; margin-bottom: 20px; font-size: 2rem; }
        h2 { color: #38bdf8; margin: 30px 0 15px; font-size: 1.5rem; border-bottom: 2px solid #1e293b; padding-bottom: 10px; }
        .card { background: #1e293b; border-radius: 12px; padding: 20px; margin-bottom: 20px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }
        .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        .stat { display: flex; justify-content: space-between; padding: 10px 0; border-bottom: 1px solid #334155; }
        .stat:last-child { border-bottom: none; }
        .stat-label { color: #94a3b8; }
        .stat-value { color: #38bdf8; font-weight: bold; }
        .status-ok { color: #22c55e; }
        .status-warn { color: #eab308; }
        .status-error { color: #ef4444; }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #334155; }
        th { color: #38bdf8; font-weight: 600; }
        tr:hover { background: #334155; }
        .timestamp { text-align: center; color: #64748b; margin-top: 40px; font-size: 0.9rem; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 20px; font-size: 0.85rem; }
        .badge-green { background: #166534; color: #22c55e; }
        .badge-red { background: #991b1b; color: #ef4444; }
        .progress-bar { background: #334155; border-radius: 10px; height: 20px; overflow: hidden; }
        .progress-fill { height: 100%; border-radius: 10px; transition: width 0.3s; }
    </style>
</head>
<body>
    <div class="container">
        <h1> acli System Report</h1>
        <p style="color:#64748b;">Generated by acli v1.0.1</p>

        <h2> System Information</h2>
        <div class="grid">
            <div class="card">
                <h3 style="color:#38bdf8;margin-bottom:15px;">Platform</h3>
                <div class="stat">
                    <span class="stat-label">Operating System</span>
                    <span class="stat-value">{{.OS}}</span>
                </div>
                <div class="stat">
                    <span class="stat-label">Architecture</span>
                    <span class="stat-value">{{.Arch}}</span>
                </div>
                <div class="stat">
                    <span class="stat-label">Go Version</span>
                    <span class="stat-value">{{.GoVersion}}</span>
                </div>
            </div>
            <div class="card">
                <h3 style="color:#38bdf8;margin-bottom:15px;">Host</h3>
                <div class="stat">
                    <span class="stat-label">Hostname</span>
                    <span class="stat-value">{{.Hostname}}</span>
                </div>
                <div class="stat">
                    <span class="stat-label">Timestamp</span>
                    <span class="stat-value">{{.Timestamp}}</span>
                </div>
            </div>
        </div>

        <h2> Network Information</h2>
        <div class="card">
            <table>
                <thead>
                    <tr>
                        <th>Interface</th>
                        <th>IP Address</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    {{range .Interfaces}}
                    <tr>
                        <td>{{.Name}}</td>
                        <td>{{.IP}}</td>
                        <td><span class="badge badge-green">UP</span></td>
                    </tr>
                    {{end}}
                </tbody>
            </table>
        </div>

        <h2> Quick Commands</h2>
        <div class="card">
            <table>
                <thead>
                    <tr>
                        <th>Command</th>
                        <th>Description</th>
                    </tr>
                </thead>
                <tbody>
                    <tr><td>acli ip</td><td>Show local IP addresses</td></tr>
                    <tr><td>acli port 8080</td><td>Check if port 8080 is in use</td></tr>
                    <tr><td>acli ps</td><td>List running processes</td></tr>
                    <tr><td>acli netstat</td><td>Show network connections</td></tr>
                    <tr><td>acli dns github.com</td><td>DNS lookup for domain</td></tr>
                    <tr><td>acli ping 8.8.8.8</td><td>Ping a host</td></tr>
                    <tr><td>acli scan localhost</td><td>Scan common ports</td></tr>
                    <tr><td>acli sysinfo</td><td>Show system information</td></tr>
                    <tr><td>acli monitor</td><td>Process monitor (htop-like)</td></tr>
                </tbody>
            </table>
        </div>

        <p class="timestamp">Generated at {{.Timestamp}} by unicli</p>
    </div>
</body>
</html>`

	type InterfaceInfo struct {
		Name string
		IP   string
	}

	type ReportData struct {
		OS         string
		Arch       string
		GoVersion  string
		Hostname   string
		Timestamp  string
		Interfaces []InterfaceInfo
	}

	hostname, _ := os.Hostname()

	ifaces, _ := net.Interfaces()
	var ifaceList []InterfaceInfo
	for _, iface := range ifaces {
		if iface.Flags&net.FlagUp == 0 {
			continue
		}
		addrs, _ := iface.Addrs()
		for _, addr := range addrs {
			if ipnet, ok := addr.(*net.IPNet); ok && ipnet.IP.To4() != nil {
				ifaceList = append(ifaceList, InterfaceInfo{
					Name: iface.Name,
					IP:   ipnet.IP.String(),
				})
			}
		}
	}

	data := ReportData{
		OS:         runtime.GOOS,
		Arch:       runtime.GOARCH,
		GoVersion:  runtime.Version(),
		Hostname:   hostname,
		Timestamp:  time.Now().Format(time.RFC3339),
		Interfaces: ifaceList,
	}

	tmpl, err := template.New("report").Parse(htmlTemplate)
	if err != nil {
		fmt.Printf("Error parsing template: %v\n", err)
		os.Exit(1)
	}

	f, err := os.Create(outputFile)
	if err != nil {
		fmt.Printf("Error creating file: %v\n", err)
		os.Exit(1)
	}
	defer f.Close()

	err = tmpl.Execute(f, data)
	if err != nil {
		fmt.Printf("Error writing template: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("HTML report generated: %s\n", outputFile)
}
